version: "3.9"
services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      main:
        aliases:
          - mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: passwordExample
  nextjs-app:
    build: ./app
    ports:
      - 4000:3000
    environment:
      DATABASE_URL: "mysql://root:passwordExample@mysqldb:3306/myDatabase"
    networks:
      - main

networks:
  main:
    name: main